POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstName":"Liviu",
    "lastName":"Nicu",
    "email":"liviu@email.com",
    "password":"password123"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"liviu@email.com",
    "password":"password123"
}


###
GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpdml1QGVtYWlsLmNvbSIsIl9pZCI6IjYwZWMyMmUzMDg2MTYxNzEwYzdjMjVjMyIsImlhdCI6MTYyNjA5MTAwNSwiZXhwIjoxNjI2MTc3NDA1fQ.yTRsEJv9XEUb0gueBXmfb4qRW9sMwBmvUhzUNK80h3U

###
GET http://localhost:3000/api/user/60ec061a7feaf73950178d34
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpdml1QGVtYWlsLmNvbSIsIl9pZCI6IjYwZWMyMmUzMDg2MTYxNzEwYzdjMjVjMyIsImlhdCI6MTYyNjA5MTAwNSwiZXhwIjoxNjI2MTc3NDA1fQ.yTRsEJv9XEUb0gueBXmfb4qRW9sMwBmvUhzUNK80h3U

###
GET http://localhost:3000/api/employee/all
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpdml1QGVtYWlsLmNvbSIsIl9pZCI6IjYwZWMyMmUzMDg2MTYxNzEwYzdjMjVjMyIsImlhdCI6MTYyNjYxOTg0MCwiZXhwIjoxNjI2NzA2MjQwfQ.EiNl4jw4LJkUqelPM3MeZonIsqLwLyd1jGQXPYaun5g


###
POST http://localhost:3000/api/employee/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpdml1QGVtYWlsLmNvbSIsIl9pZCI6IjYwZWMyMmUzMDg2MTYxNzEwYzdjMjVjMyIsImlhdCI6MTYyNjYxOTg0MCwiZXhwIjoxNjI2NzA2MjQwfQ.EiNl4jw4LJkUqelPM3MeZonIsqLwLyd1jGQXPYaun5g


{
    "email":"liviu@email.com",
    "name":"Test Liviu"
}

###
GET http://localhost:3000/api/employee/getById/60f44082e3998d1008224d01
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpdml1QGVtYWlsLmNvbSIsIl9pZCI6IjYwZWMyMmUzMDg2MTYxNzEwYzdjMjVjMyIsImlhdCI6MTYyNjYxOTg0MCwiZXhwIjoxNjI2NzA2MjQwfQ.EiNl4jw4LJkUqelPM3MeZonIsqLwLyd1jGQXPYaun5g

###
POST http://localhost:3000/api/employee/update/60f44082e3998d1008224d01
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpdml1QGVtYWlsLmNvbSIsIl9pZCI6IjYwZWMyMmUzMDg2MTYxNzEwYzdjMjVjMyIsImlhdCI6MTYyNjYxOTg0MCwiZXhwIjoxNjI2NzA2MjQwfQ.EiNl4jw4LJkUqelPM3MeZonIsqLwLyd1jGQXPYaun5g


{
    "email":"liviu@email.com",
    "name":"Test Liviu updated"
}

###
DELETE http://localhost:3000/api/employee/delete/60f44082e3998d1008224d01
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpdml1QGVtYWlsLmNvbSIsIl9pZCI6IjYwZWMyMmUzMDg2MTYxNzEwYzdjMjVjMyIsImlhdCI6MTYyNjYxOTg0MCwiZXhwIjoxNjI2NzA2MjQwfQ.EiNl4jw4LJkUqelPM3MeZonIsqLwLyd1jGQXPYaun5g

###
POST http://localhost:3000/api/inventory/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpdml1QGVtYWlsLmNvbSIsIl9pZCI6IjYwZWMyMmUzMDg2MTYxNzEwYzdjMjVjMyIsImlhdCI6MTYyNjY3ODI0OSwiZXhwIjoxNjI2NzY0NjQ5fQ.rnmVuFYYMzzQqWjT80Tpt7yfFt2wHZ1NqGgsorqECbo

{"name":"HP Laptop","invetoryCode":"3132123","category":"Laptop","quantity":2}

###
GET http://localhost:3000/api/inventory/all?page=0&size=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpdml1QGVtYWlsLmNvbSIsIl9pZCI6IjYwZWMyMmUzMDg2MTYxNzEwYzdjMjVjMyIsImlhdCI6MTYyNjY3ODI0OSwiZXhwIjoxNjI2NzY0NjQ5fQ.rnmVuFYYMzzQqWjT80Tpt7yfFt2wHZ1NqGgsorqECbo
###
POST http://localhost:3000/api/inventory/addEmployee
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpdml1QGVtYWlsLmNvbSIsIl9pZCI6IjYwZWMyMmUzMDg2MTYxNzEwYzdjMjVjMyIsImlhdCI6MTYyNjYxOTg0MCwiZXhwIjoxNjI2NzA2MjQwfQ.EiNl4jw4LJkUqelPM3MeZonIsqLwLyd1jGQXPYaun5g


{
    "inventoryId":"60f52400f648b953a4c81f09",
    "employeeId":"60f33c8018f75d39301b3a1d"
}

###
GET http://localhost:3000/api/inventory/readXlsx
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxpdml1QGVtYWlsLmNvbSIsIl9pZCI6IjYwZWMyMmUzMDg2MTYxNzEwYzdjMjVjMyIsImlhdCI6MTYyNjY3ODI0OSwiZXhwIjoxNjI2NzY0NjQ5fQ.rnmVuFYYMzzQqWjT80Tpt7yfFt2wHZ1NqGgsorqECbo
